import Head from 'next/head'
import {useState} from 'react'
import FieldList from '../components/Field/FieldList'
import TimestampList from '../components/Timestamp/TimestampList'
import TimestampNew from '../components/Timestamp/TimestampNew'
import BookingList from '../components/Booking/BookingList'
import { Inter } from '@next/font/google'
import { Provider } from "react-redux";
import { combineReducers, configureStore } from "@reduxjs/toolkit"
import bookingReducer from '../slices/BookingSlice'
import fieldReducer from '../slices/FieldInfoSlice'
import timestampReducer from '../slices/TimestampSlice'

const inter = Inter({ subsets: ['latin'] })

const rootReducer = combineReducers({
  field: fieldReducer,
  timestamp: timestampReducer,
  booking: bookingReducer,
})

const store = configureStore({
  reducer: {
    rootReducer,
  }
});

export default function Home() {
  const [openTimestamp, setOpenTimestamp] = useState(false)
  const [currentTab, setCurrentTab] = useState('1')

  const handleTab = (e) => {
    setCurrentTab(e.target.id)
    setOpenTimestamp(false)
  }

  return (
    <>
      <Head>
        <title>Quản lý sân bóng</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Provider store={store}>
        <main name="container" className="p-2">
          <div className="flex items-center space-x-4 rounded-tl-xl rounded-tr-xl translate-y-0.5">
            <button 
              className={`${currentTab === '1' ? "border-2 border-b-0 border-blue-500 bg-black " : null} flex justify-center items-center text-lg font-bold px-6 py-4 rounded-tr-lg rounded-tl-lg w-56`} 
              id="1" 
              disable={(currentTab === '1').toString()} 
              onClick={handleTab}
            >
              <iconify-icon icon="mdi:soccer-field"></iconify-icon>
              <span className="ml-2">Sân bóng</span>
            </button>
            <button 
              className={`${currentTab === '2' ? "border-2 border-b-0 border-blue-500 bg-black " : null} flex justify-center items-center text-lg font-bold px-6 py-4 rounded-tr-lg rounded-tl-lg w-56`} 
              id="2" 
              disable={(currentTab === '2').toString()} 
              onClick={handleTab}
            >
              <iconify-icon icon="material-symbols:event-note-outline-rounded"></iconify-icon>
              <span className="ml-2">Đặt sân</span>
            </button>
          </div>
          <div name="content" className="border-2 border-blue-500 rounded-bl-xl rounded-br-xl rounded-tr-xl p-4 min-h-screen">
            {/* <input type="date" name="timeFilter" value="2023-02-22" min="2023-02-22"/> */}
            {currentTab === '1' ?
              (<div name="" className="">
                {openTimestamp ? 
                  (<div className="relative flex flex-col justify-center items-center">
                    <TimestampList/>
                    <TimestampNew/>
                    <button 
                      className="absolute top-1 right-2 flex justify-center items-center bg-blue-500 border-2 border-blue-500 rounded-full" 
                      onClick={() => setOpenTimestamp(false)}
                    >
                      <iconify-icon icon="ic:round-close"></iconify-icon>                
                    </button>
                  </div>)
                  :(<>
                    <button 
                      className="flex justify-center items-center font-bold bg-blue-500 border-2 border-blue-500 rounded-lg px-6 py-2 ml-auto mt-2 mb-6" 
                      onClick={() => setOpenTimestamp(true)}
                    >
                      <iconify-icon icon="carbon:settings"></iconify-icon>
                      <span className="ml-2">Khung giờ</span>                  
                    </button>
                    <FieldList />
                  </>)
                }
              </div>
              )
              :
              (<div name="" className="flex justify-center items-center">
                <BookingList/>
              </div>)
            }
          </div>
        </main>
      </Provider>
    </>
  )
}